        spring:
          application:
            name: employee
            main:
            allow-bean-definition-overriding: true

          datasource:
            url: jdbc:mysql://localhost:3306/emp_db?useSSL=false&allowPublicKeyRetrieval=true
            username: root
            password: root
            driver-class-name: com.mysql.cj.jdbc.Driver

          jpa:
            hibernate:
              ddl-auto: update
            properties:
              hibernate:
                dialect: org.hibernate.dialect.MySQLDialect


        logging:
          level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type: TRACE

        management:
          endpoints:
            web:
              exposure:
                include: "*"
          endpoint:
            health:
              show-details: always

        app:
          jwtSecret: appSecretKey
          jwtExpirationMs: 86400000

        skip_words: not good words,bad words,XXXX,<script,

        #spring.datasource.url=jdbc:mysql://localhost:3306/HMSSpring1?useSSL=false&allowPublicKeyRetrieval=true
        #spring.datasource.username=root
        #spring.datasource.password=root
        #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
        #Hibernate

        #The Sql dialect makes Hibernate generate better SQL for the chosen database
        #spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

        #Hibernate ddl auto (Create, create-drop, validate, update)
        #spring.jpa.hibernate.ddl-auto=update

        #logging.level.org.hibernate.SQL=DEBUG
        #logging.level.org.hibernate.type=TRACE

        #server.servlet.context-path=/hms

        #hms.app.jwtSecret= hmsSecretKey
        #hms.app.jwtExpirationMs= 86400000

        #bezkoder.app.jwtSecret= bezKoderSecretKey
        #bezkoder.app.jwtExpirationMs= 86400000
        #HMSSpring1
